{
 "title": "INFLUX JMeter DASHBOARD",
 "description": "Monitor your Apache JMeter load test in real time with InfluxDB and Grafana.\r\nGet overall summary, errors details and particular transaction response times.",
 "tags": [ "load_test" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "influxdb" },
   { "name": "measurement_name", "label": "Measurement name", "query": "jmeter" },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5,10,20,30,40,50"
   },
   { "name": "scope", "query": "2,3,4,5,6,7,8,9,10,15,20,40" },
   { "name": "step", "label": "step (seconds)", "query": "30,40,60,90,120,150,170,300" },
   {
    "name": "application",
    "query": "select distinct(\"application\") FROM (SELECT first(\"count\") FROM /^$measurement_name$/ WHERE $timeFilter GROUP BY \"application\")"
   },
   {
    "name": "main_transaction",
    "query": "select distinct(\"transaction\") FROM (SELECT first(\"count\") FROM /^$measurement_name$/ WHERE  \"application\" =~ /^${application:regex}$/  AND \"transaction\"=~/^(А|Б|Г|Д|Е|Ё|Ж|З|Й|К|Л|М|Н|О|П|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ|Ы|Э|Ю|Я|Р|В|И).+\\(TC\\)$/ OR \"transaction\"=~/^.+\\(TG\\)$/ AND $timeFilter GROUP BY \"transaction\")"
   },
   {
    "name": "transaction",
    "query": "select distinct(\"transaction\") FROM (SELECT first(\"count\") FROM /^$measurement_name$/ WHERE  \"application\" =~ /^${application:regex}$/ AND \"transaction\" != 'internal' AND \"transaction\" != 'all' AND \"transaction\" !~ /^${main_transaction:regex}$/ AND (\"transaction\" =~ /^.+\\(TC\\)$/ OR \"transaction\" =~ /^.+?SLA.*$/ OR \"transaction\" =~ /^.+?Запрос-выписки-за-день-всего.*$/)  AND $timeFilter GROUP BY \"transaction\")"
   },
   {
    "name": "request",
    "query": "select distinct(\"transaction\") FROM (SELECT first(\"count\") FROM /^$measurement_name$/ WHERE  \"application\" =~ /^${application:regex}$/ AND \"transaction\" != 'internal' AND \"transaction\" != 'all' AND \"transaction\" !~ /^.+\\(TC\\)$/ AND \"transaction\" !~ /^.+?SLA.*$/ AND \"transaction\" !~ /^.+?Запрос-выписки-за-день-всего.*$/ AND \"transaction\" !~ /^${main_transaction:regex}$/ AND $timeFilter GROUP BY \"transaction\")"
   },
   {
    "name": "generator",
    "label": "generator",
    "query": "select distinct(\"generatorHost\") FROM (SELECT first(\"count\") FROM /^$measurement_name$/ WHERE  \"application\" =~ /^${application:regex}$/  AND $timeFilter GROUP BY \"generatorHost\")"
   },
   {
    "name": "responce_code",
    "label": "responce code",
    "query": "select distinct(\"responseCode\") FROM (SELECT first(\"count\") FROM /^$measurement_name$/ WHERE (\"application\" =~ /^${application:regex}$/  AND \"responseCode\" != '0'  AND \"responseCode\" != '' ) AND $timeFilter GROUP BY \"responseCode\")"
   },
   { "name": "group_filter", "query": "rupayment,statement" }
  ]
 },
 "panels": [
  { "title": "Menu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Меню запусков тестов (последние 30 дней)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"application\", \"testId\", \"title\", time as \"start\" from (select first(text), time from \"events\" where time > now()-190d group by \"application\", \"testId\", \"title\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"testId\", time as \"stop\" from (select last(text), time from \"events\" where time > now()-190d group by \"application\", \"testId\", \"title\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Метрики по транзакциям",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "/^$measurement_name$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Time mean (ok+ko)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "/^$measurement_name$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "/^$measurement_name$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "OK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "/^$measurement_name$/",
     "query": "SELECT \n    max(\"TPS\") as \"TPS (max)\",\n    mean(\"TPS\") as \"TPS (mean)\",\n    max(\"Mean Time\") as \"Time (max)\",\n    mean(\"Mean Time\") as \"Time (mean)\",\n    max(\"90% Time\") as \"90% (max)\",\n    mean(\"90% Time\") as \"90% (mean)\"\nFROM (\n        SELECT  \n\t    sum(\"count\") / ${step} AS \"TPS\", \n            mean(\"avg\") AS \"Mean Time\", \n            max(\"pct90.0\") AS \"90% Time\"\n        FROM ${measurement_name} \n        WHERE (\"statut\" = 'ok' AND \"transaction\" =~ /^${main_transaction:regex}$/  AND \"application\" =~ /^${application:regex}$/ AND \"generatorHost\" =~ /^${generator:regex}$/) AND $timeFilter \n        GROUP BY time(${step}s), \"transaction\"\n)\nWHERE  $timeFilter GROUP BY \"transaction\"\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / ${step}" ], "type": "math" },
       { "params": [ "TPS" ], "type": "alias" }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${step}" ], "type": "math" },
       { "params": [ "Mean Time" ], "type": "alias" }
      ],
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${step}" ], "type": "math" },
       { "params": [ "90% Time" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       },
       { "params": [ "stddev TPS" ], "type": "alias" }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       },
       { "params": [ "stddev Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^.*\\(TC\\)$/" },
      { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Threads-$tag_generatorHost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "generatorHost" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_name$/",
     "select": [
      [
       { "params": [ "meanAT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "internal" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "All",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "generatorHost" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_name$/",
     "query": "SELECT sum(\"AT\") as \"sum\" FROM\n(SELECT mean(\"meanAT\") as \"AT\" FROM /^$measurement_name$/ WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval), \"generatorHost\" fill(null))\nGROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "meanAT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "internal" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Active Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"AT\") as \"sum\" FROM\n(SELECT mean(\"meanAT\") as \"AT\" FROM /^$measurement_name$/ WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval), \"generatorHost\" fill(null))\nGROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Успешные транзакции",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ (${step})" ], "type": "math" },
       { "params": [ " (avg ${step}s)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "$tag_transaction (raw)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "${scope}" ], "type": "moving_average" },
       { "params": [ "  / ($__interval_ms / 1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Успешные транзакции (в час)",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " *3600 / (${step})" ], "type": "math" },
       { "params": [ "OK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Неуспешные транзакции",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ (${step})" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "$tag_transaction (raw)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "${scope}" ], "type": "moving_average" },
       { "params": [ "  / ($__interval_ms / 1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Неуспешные транзакции (в час)",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 30 },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " *3600 / (${step})" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Неуспешные транзакции (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT max(\"KO\")/ max(\"TOTAL\") as \"KO%\" FROM\n(SELECT sum(\"count\") / (${step}) AS \"TOTAL\" FROM \"jmeter\" WHERE (\"application\" =~ /^${application:regex}$/ AND \"transaction\" =~ /^${main_transaction:regex}$/ AND \"statut\" = 'all') AND $timeFilter GROUP BY time(${step}s), \"transaction\" fill(0)),\n(SELECT sum(\"count\") / (${step}) AS \"KO\" FROM \"jmeter\" WHERE (\"application\" =~ /^${application:regex}$/ AND \"transaction\" =~ /^${main_transaction:regex}$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY time(${step}s), \"transaction\" fill(0))\nWHERE $timeFilter GROUP BY time(${step}s), \"transaction\" fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ (${step})" ], "type": "math" },
       { "params": [ "KO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "$tag_transaction $col",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT max(\"KO\")/ max(\"TOTAL\") as \"(raw)\" FROM\n(SELECT moving_average(sum(\"count\"), ${scope}) as \"KO\" FROM \"jmeter\" WHERE (\"application\" =~ /^${application}$/ AND \"transaction\" =~ /^${main_transaction}$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY time($__interval), \"transaction\" fill(0)),\n(SELECT moving_average(sum(\"count\"), ${scope})  AS \"TOTAL\" FROM \"jmeter\" WHERE (\"application\" =~ /^${application:regex}$/ AND \"transaction\" =~ /^${main_transaction:regex}$/ AND \"statut\" = 'all') AND $timeFilter GROUP BY  time($__interval), \"transaction\" fill(0))\nWHERE $timeFilter GROUP BY  time($__interval), \"transaction\" fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ (${step})" ], "type": "math" },
       { "params": [ "KO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Неуспешные транзакции (%)",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 38 },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"KO\")/max(\"TOTAL\") as \"KO%\" FROM\n(SELECT sum(\"count\")  AS \"TOTAL\" FROM \"jmeter\" WHERE (\"application\" =~ /^${application:regex}$/ AND \"transaction\" =~ /^${main_transaction:regex}$/ AND \"statut\" = 'all') AND $timeFilter GROUP BY \"transaction\" fill(0)),\n(SELECT sum(\"count\")  AS \"KO\" FROM \"jmeter\" WHERE (\"application\" =~ /^${application:regex}$/ AND \"transaction\" =~ /^${main_transaction:regex}$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY \"transaction\" fill(0))\nWHERE $timeFilter GROUP BY \"transaction\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Threads-$tag_generatorHost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "generatorHost" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_name$/",
     "select": [
      [
       { "params": [ "meanAT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "internal" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "All",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "generatorHost" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_name$/",
     "query": "SELECT sum(\"AT\") as \"sum\" FROM\n(SELECT mean(\"meanAT\") as \"AT\" FROM /^$measurement_name$/ WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval), \"generatorHost\" fill(null))\nGROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "meanAT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "internal" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Active Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"AT\") as \"sum\" FROM\n(SELECT mean(\"meanAT\") as \"AT\" FROM /^$measurement_name$/ WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval), \"generatorHost\" fill(null))\nGROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Времена отклика (90-й персентиль)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    },
    {
     "alias": "$tag_transaction (raw)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "${scope}" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Времена отклика (90-й персентиль)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 52 },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_name$/",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Времена отклика (90-й персентиль)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    },
    {
     "alias": "$tag_transaction (raw)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "${scope}" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Времена отклика (90-й персентиль)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 61 },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_name$/",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Времена отклика (среднее)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    },
    {
     "alias": "$tag_transaction (raw)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "${scope}" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Времена отклика (среднее)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 70 },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "${step}s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_name$/",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Количество пользователей, ожидающих ответы сервера",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "* sum(count) / (${__interval_ms})"
        ],
        "type": "math"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
      { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
     ]
    },
    {
     "alias": "All",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"AT\") as \"sum\" FROM\n(SELECT mean(\"meanAT\") as \"AT\" FROM /^$measurement_name$/ WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval), \"generatorHost\" fill(null))\nGROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"countError\")  FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" = 'all') AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 14, "x": 5, "y": 3 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "alias": "Num of Errors (raw)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ($__interval_ms / 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      },
      {
       "alias": "Num of Errors",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/${step}" ], "type": "math" },
         { "params": [ " (avg ${step}s)" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Error Rate %",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$application$/ AND $timeFilter GROUP BY time($__interval) fill(null))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Ошибочные транзакции: Интенсивность",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/ ${step}" ], "type": "math" },
         { "params": [ " (avg ${step}s)" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "Ошибочные транзакции: Интенсивность",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ${step}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
       ]
      }
     ]
    },
    {
     "title": "Ошибочные запросы: Интенсивность",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ${step}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
       ]
      }
     ]
    },
    {
     "title": "Error % - доля неуспешных запросов",
     "type": "table",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "all" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "ko" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "Error count (group by Response Code)",
     "type": "table",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "responseCode" ], "type": "tag" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/^$responce_code$/" }
       ]
      }
     ]
    },
    {
     "title": "Assertion Failed",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "responseMessage" ], "type": "tag" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "=", "value": "Assertion failed" }
       ]
      }
     ]
    },
    {
     "title": "Error count (group by Response Code, Response Message)",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "responseMessage" ], "type": "tag" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "responseCode" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/^$responce_code$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"count\")  FROM \"$measurement_name\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Received Bytes",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"rb\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sent Bytes",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"sb\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Read + Send",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "rb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / (${step}) + sum(sb) / (${step})"
          ],
          "type": "math"
         },
         { "params": [ "read + send" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Read",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "rb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / (${step})" ], "type": "math" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Send",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / (${step})" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Network Traffic (read)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "rb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ${step}" ], "type": "math" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Traffic (read)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "rb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ($__interval_ms / 1000)" ], "type": "math" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Traffic (send)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / (${step})" ], "type": "math" },
         { "params": [ "send" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Traffic (send)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / (${__interval_ms}/1000)" ], "type": "math" },
         { "params": [ "send" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Traffic (send)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "send" ], "type": "alias" }
        ],
        [
         { "params": [ "rb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction (All)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики по транзакциям (Old Table)",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 23, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1000h" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " * mean(avg)" ], "type": "math" },
         { "params": [ "Total Time" ], "type": "alias" }
        ],
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1000h" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Errors" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT\nfirst(\"OK\") as \"OK\",\nfirst(\"TPS max*\") as \"TPS max*\",\nfirst(\"TPS*\") as \"TPS*\",\nfirst(\"90% max*\") as \"90% max*\",\nfirst(\"90%*\") as \"90%*\",\nfirst(\"Time max*\") as \"Time max*\",\nfirst(\"Time*\") as \"Time*\"\nFROM(\nSELECT \nsum(\"Count\") AS \"OK\",\nmax(\"TPS\") as \"TPS max*\",\nmean(\"TPS\") as \"TPS*\",\nmax(\"Mean Time\") as \"Time max*\",\nmean(\"Mean Time\") as \"Time*\",\nmax(\"90% Time\") as \"90% max*\",\nmean(\"90% Time\") as \"90%*\"\nFROM (\nSELECT  \nsum(\"count\") AS \"Count\",  \n(sum(\"count\") / ${step}) AS \"TPS\", \n(mean(\"avg\")) AS \"Mean Time\", \n(max(\"pct90.0\")) AS \"90% Time\"\nFROM ${measurement_name} WHERE (\"statut\" = 'ok' AND \"application\" =~ /^${application:regex}$/ AND \"transaction\" =~ /^${transaction:regex}$/ AND \"generatorHost\" =~ /^${generator:regex}$/) AND $timeFilter GROUP BY time(${step}s), \"transaction\"\n) WHERE  $timeFilter GROUP BY \"transaction\"\n) WHERE  $timeFilter GROUP BY time(1000h), \"transaction\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Метрики по транзакциям",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 17 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Time mean (ok+ko)" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Errors" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
     "options": {
      "content": "<h1 style=\"text-align:center\">\n    Усредненные метрики за интервал ${step} секунд\n</h1>"
     }
    },
    {
     "title": "TPS: Интенсивность (средняя)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ${step}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
       ]
      }
     ]
    },
    {
     "title": "TPS: Интенсивность",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "${scope}" ], "type": "moving_average" },
         { "params": [ " / (${__interval_ms}/1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "90%: Времена отклика (средние)",
     "type": "graph",
     "description": "Максимальное значение 90% за интервал времени ${step} секунд:\n\n1. Для интервала ${send_interval}s вычислились метрики 90% времени отклика\n2. Для нескольких таких интервалов ${send_interval}s, которые вошли в общий интервал ${step}s выбирается максимальное значение метрики 90%\n3. Метрика отображается на графике",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "90%: Времена отклика",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "${scope}" ], "type": "moving_average" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Time: Времена отклика (среднее)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Requests (All)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики по транзакциям (Old Table)",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1000h" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "query": "SELECT sum(\"Total Time\") as \"Total Time\" FROM (\nSELECT sum(\"count\")  * mean(avg) AS \"Total Time\" FROM /^$measurement_name$/ WHERE (\"application\" =~ /^${application:regex}$/ AND \"transaction\" =~ /^${request:regex}$/ AND \"generatorHost\" =~ /^${generator:regex}$/ AND \"statut\" = 'all') AND $timeFilter GROUP BY time(5s), \"transaction\")\nGROUP BY time(1000h), \"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " * mean(avg)" ], "type": "math" },
         { "params": [ "Total Time" ], "type": "alias" }
        ],
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1000h" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "1000h" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Errors" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT\nsum(\"Count\") AS \"OK\",\nmax(\"TPS\") as \"TPS max*\",\nmean(\"TPS\") as \"TPS*\",\nmax(\"Mean Time\") as \"Time max*\",\nmean(\"Mean Time\") as \"Time*\",\nmax(\"90% Time\") as \"90% max*\",\nmean(\"90% Time\") as \"90%*\"\nFROM (\nSELECT  \nsum(\"count\") AS \"Count\",  \n(sum(\"count\") / ${step}) AS \"TPS\", \n(mean(\"avg\")) AS \"Mean Time\", \n(max(\"pct90.0\")) AS \"90% Time\"\nFROM ${measurement_name} WHERE (\"statut\" = 'ok' AND \"application\" =~ /^${application:regex}$/ AND \"transaction\" =~ /^${request:regex}$/ AND \"generatorHost\" =~ /^${generator:regex}$/) AND $timeFilter GROUP BY time(${step}s), \"transaction\"\n) WHERE  $timeFilter GROUP BY time(1000h), \"transaction\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Метрики по запросам",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Time mean (ok+ko)" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Errors" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      },
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "query": "SELECT \nsum(\"Count\") AS \"OK\",\nmax(\"TPS\") as \"TPS (max)\",\nmean(\"TPS\") as \"TPS (mean)\",\nmax(\"Mean Time\") as \"Time (max)\",\nmean(\"Mean Time\") as \"Time (mean)\",\nmax(\"90% Time\") as \"90% (max)\",\nmean(\"90% Time\") as \"90% (mean)\"\nFROM (\nSELECT  \nsum(\"count\") AS \"Count\",  \n(sum(\"count\") / ${step}) AS \"TPS\", \n(mean(\"avg\")) AS \"Mean Time\", \n(max(\"pct90.0\")) AS \"90% Time\"\nFROM ${measurement_name} WHERE (\"statut\" = 'ok' AND \"application\" =~ /^${application:regex}$/ AND \"transaction\" =~ /^${request:regex}$/ AND \"generatorHost\" =~ /^${generator:regex}$/) AND $timeFilter GROUP BY time(${step}s), \"transaction\"\n) WHERE  $timeFilter GROUP BY \"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ${step}" ], "type": "math" },
         { "params": [ "TPS" ], "type": "alias" }
        ],
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${step}" ], "type": "math" },
         { "params": [ "Mean Time" ], "type": "alias" }
        ],
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${step}" ], "type": "math" },
         { "params": [ "90% Time" ], "type": "alias" }
        ],
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "stddev"
         },
         { "params": [ "stddev TPS" ], "type": "alias" }
        ],
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "stddev"
         },
         { "params": [ "stddev Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^.*\\(TC\\)$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
     "options": {
      "content": "<h1 style=\"text-align:center\">\n    Усредненные метрики за интервал ${step} секунд\n</h1>"
     }
    },
    {
     "title": "TPS: Интенсивность (средняя)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ${step}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
       ]
      }
     ]
    },
    {
     "title": "TPS: Интенсивность",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "${scope}" ], "type": "moving_average" },
         { "params": [ " / (${__interval_ms}/1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "90%: Времена отклика (средние)",
     "type": "graph",
     "description": "Максимальное значение 90% за интервал времени ${step} секунд:\n\n1. Для интервала ${send_interval}s вычислились метрики 90% времени отклика\n2. Для нескольких таких интервалов ${send_interval}s, которые вошли в общий интервал ${step}s выбирается максимальное значение метрики 90%\n3. Метрика отображается на графике",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "90%: Времена отклика",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "${scope}" ], "type": "moving_average" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Time: Времена отклика (среднее)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
       ]
      }
     ]
    },
    {
     "title": "Time: Суммарное время отклика (по успешным запросам)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [
           "* sum(count) / (${__interval_ms}/1000)"
          ],
          "type": "math"
         },
         { "params": [ "total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
       ]
      }
     ]
    },
    {
     "title": "Количество пользователей, обрабатывающих запросы",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [
           "* sum(count) / (${__interval_ms})"
          ],
          "type": "math"
         },
         { "params": [ "total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction ($group_filter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "repeat": "group_filter",
   "collapsed": true,
   "panels": [
    {
     "title": "Метрики по транзакциям (${group_filter})",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 208 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Time mean (ok+ko)" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^${group_filter:regex}.*$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Errors" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^${group_filter:regex}.*$/" }
       ]
      },
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "/^$measurement_name$/",
       "query": "SELECT \nsum(\"Count\") AS \"OK\",\nmax(\"TPS\") as \"TPS (max)\",\nmean(\"TPS\") as \"TPS (mean)\",\nmax(\"Mean Time\") as \"Time (max)\",\nmean(\"Mean Time\") as \"Time (mean)\",\nmax(\"90% Time\") as \"90% (max)\",\nmean(\"90% Time\") as \"90% (mean)\"\nFROM (\nSELECT  \nsum(\"count\") AS \"Count\",  \n(sum(\"count\") / ${step}) AS \"TPS\", \n(mean(\"avg\")) AS \"Mean Time\", \n(max(\"pct90.0\")) AS \"90% Time\"\nFROM ${measurement_name} WHERE (\"statut\" = 'ok' AND \"transaction\" =~ /^${transaction:regex}$/ AND \"transaction\" !~ /^${main_transaction:regex}$/ AND \"transaction\" =~ /^${group_filter:regex}.*$/ AND \"generatorHost\" =~ /^${generator:regex}$/) AND $timeFilter GROUP BY time(${step}s), \"transaction\"\n) WHERE  $timeFilter GROUP BY \"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ${step}" ], "type": "math" },
         { "params": [ "TPS" ], "type": "alias" }
        ],
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${step}" ], "type": "math" },
         { "params": [ "Mean Time" ], "type": "alias" }
        ],
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${step}" ], "type": "math" },
         { "params": [ "90% Time" ], "type": "alias" }
        ],
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "stddev"
         },
         { "params": [ "stddev TPS" ], "type": "alias" }
        ],
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "stddev"
         },
         { "params": [ "stddev Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^.*\\(TC\\)$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 222 },
     "options": {
      "content": "<h1 style=\"text-align:center\">\n    Усредненные метрики за интервал ${step} секунд\n</h1>"
     }
    },
    {
     "title": "TPS: Интенсивность (средняя)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 224 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ${step}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^${group_filter:regex}.*$/" }
       ]
      }
     ]
    },
    {
     "title": "TPS: Интенсивность",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 232 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "${scope}" ], "type": "moving_average" },
         { "params": [ " / (${__interval_ms}/1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^${group_filter:regex}.*$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "90%: Времена отклика (средние)",
     "type": "graph",
     "description": "Максимальное значение 90% за интервал времени ${step} секунд:\n\n1. Для интервала ${send_interval}s вычислились метрики 90% времени отклика\n2. Для нескольких таких интервалов ${send_interval}s, которые вошли в общий интервал ${step}s выбирается максимальное значение метрики 90%\n3. Метрика отображается на графике",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 240 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^${group_filter:regex}.*$/" }
       ]
      }
     ]
    },
    {
     "title": "90%: Времена отклика",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 248 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "${scope}" ], "type": "moving_average" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^${group_filter:regex}.*$/" }
       ]
      }
     ]
    },
    {
     "title": "Time: Времена отклика (среднее)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 256 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "${step}s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
        { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/^$main_transaction$/" },
        { "condition": "AND", "key": "generatorHost", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^${group_filter:regex}.*$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}