{
 "title": "PostgreSQL Activity",
 "tags": [
  "influxdb",
  "PostgreSQL",
  "main"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "current",
    "query": "/d/pgstat/postgresql-query-statistics"
   },
   {
    "name": "detail",
    "query": "/d/pgquery/postgresql-query-details"
   },
   { "name": "db_jmeter", "label": "DataBase for annotation", "query": "influxdb" },
   { "name": "db", "label": "DataBase", "query": "influxdb" },
   { "name": "archive", "label": "Retention policy (archive)", "query": "SHOW RETENTION POLICIES" },
   { "name": "new", "label": "Retention Policy (new)", "query": "SHOW RETENTION POLICIES" },
   {
    "name": "host",
    "label": "PostgreSQL host",
    "query": "SELECT DISTINCT(\"host\") FROM (SELECT last(\"count\") FROM \"${new}\".\"pg_stat_activity_count\"  WHERE $timeFilter GROUP BY \"host\")"
   },
   {
    "name": "datname",
    "label": "PostgreSQL DB",
    "query": "SELECT DISTINCT(\"datname\") FROM (SELECT last(\"count\") FROM \"${new}\".\"pg_stat_activity_count\" WHERE \"host\" =~ /^${host:regex}$/   AND $timeFilter GROUP BY \"datname\")"
   },
   {
    "name": "usename",
    "label": "PostgreSQL User",
    "query": "SELECT DISTINCT(\"usename\") FROM (SELECT last(\"count\") FROM \"${new}\".\"pg_stat_activity_count\" WHERE \"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/  AND $timeFilter GROUP BY \"usename\")"
   },
   {
    "name": "state",
    "label": "state",
    "query": "SELECT DISTINCT(\"state\") FROM (SELECT last(\"count\") FROM \"${new}\".\"pg_stat_activity_count\" WHERE \"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/  AND $timeFilter GROUP BY \"state\")"
   },
   { "name": "TOP", "query": "10,20,30,40,50,100,200" },
   { "name": "TOP_by", "label": "TOP by", "query": "Total, Max, Mean, Count" },
   {
    "name": "filter",
    "label": "Filter",
    "query": "SELECT \"query_md5\", top(\"${TOP_by}\", ${TOP}) \nFROM (SELECT sum(\"transaction_duration\") AS \"Total\", mean(\"transaction_duration\") AS \"Mean\", count(\"transaction_duration\") AS \"Count\" FROM \"$new\".\"pg_stat_activity\" WHERE (\"state\" = 'idle in transaction' AND \"host\" =~ /^$host$/ AND \"datname\" =~ /^$datname$/ AND \"usename\" =~ /^$usename$/) AND $timeFilter GROUP BY  \"query_md5\") "
   },
   { "name": "db_stat", "label": "DataBase Stat", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Idle in transaction - Sum Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Idle in transaction Duration by host",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"host\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by state",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"state\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by datname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"datname\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by usename",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"usename\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by host — datname — usename",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host — $tag_datname — $tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by usename — query_md5",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_usename — $tag_query_md5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"usename\", \"query_md5\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by state — datname — usename — query_md5 — query",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "query" ], "type": "tag" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "sum_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*1000.0" ], "type": "math" },
         { "params": [ "Sum" ], "type": "alias" }
        ],
        [
         { "params": [ "max_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ],
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Count" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction - Sum Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Idle in transaction Connection Count by host",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Connection Count by usename",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Connection Count by datname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Connection Count by state",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Connection Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_host - $tag_datname - $tag_usename - $tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction - Avg Connection Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Idle in transaction Connection Duration by host",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_connection_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Connection Duration by usename",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_connection_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Connection Duration by datname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_connection_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Connection Duration by state",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_connection_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Connection Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host - $tag_datname - $tag_usename - $tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_connection_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction - Avg Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Idle in transaction Duration by host",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by usename",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by datname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by state",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host - $tag_datname - $tag_usename - $tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "State Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "State Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_suration\") as \"state_suration\" FROM (\nSELECT sum(\"avg_state_seconds\") as \"state_suration\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"usename\", \"datname\", \"state\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"host\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "State Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_suration\") as \"state_suration\" FROM (\nSELECT sum(\"avg_state_seconds\") as \"state_suration\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"usename\", \"datname\", \"state\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"usename\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "State Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_suration\") as \"state_suration\" FROM (\nSELECT sum(\"avg_state_seconds\") as \"state_suration\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"usename\", \"datname\", \"state\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"datname\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "State Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_suration\") as \"state_suration\" FROM (\nSELECT sum(\"avg_state_seconds\") as \"state_suration\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"usename\", \"datname\", \"state\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"state\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "State Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host - $tag_datname - $tag_usename - $tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"count\") as \"count\" FROM (\nSELECT mean(\"count\") as \"count\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND $timeFilter GROUP BY time($__interval), \"state\", \"usename\", \"datname\", \"host\" fill(null)\n) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"count\") as \"count\" FROM (\nSELECT mean(\"count\") as \"count\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND $timeFilter GROUP BY time($__interval), \"state\", \"usename\", \"datname\", \"host\" fill(null)\n) WHERE $timeFilter GROUP BY time($__interval), \"datname\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"count\") as \"count\" FROM (\nSELECT mean(\"count\") as \"count\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND $timeFilter GROUP BY time($__interval), \"state\", \"usename\", \"datname\", \"host\" fill(null)\n) WHERE $timeFilter GROUP BY time($__interval), \"state\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"count\") as \"count\" FROM (\nSELECT mean(\"count\") as \"count\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND $timeFilter GROUP BY time($__interval), \"state\", \"usename\", \"datname\", \"host\" fill(null)\n) WHERE $timeFilter GROUP BY time($__interval), \"usename\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_datname - $tag_usename - $tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}