{
 "title": "PostgreSQL Query Details",
 "tags": [
  "influxdb",
  "PostgreSQL"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "DataBase", "query": "influxdb" },
   { "name": "archive", "label": "Retention policy (archive)", "query": "archive" },
   { "name": "new", "label": "Retention Policy (new)", "query": "1d" },
   { "name": "queryid", "label": "queryid", "query": "3575890253" },
   {
    "name": "host",
    "label": "PostgreSQL host",
    "query": "SELECT DISTINCT(\"host\") FROM (SELECT last(\"calls\") FROM \"${archive}\".\"pg_stat_statements_diff_1m_archive\" WHERE \"queryid\"=~/^${queryid:regex}$/ AND $timeFilter GROUP BY \"host\")"
   },
   {
    "name": "datname",
    "label": "PostgreSQL DB",
    "query": "SELECT DISTINCT(\"datname\") FROM (SELECT last(\"calls\") FROM \"${archive}\".\"pg_stat_statements_diff_1m_archive\" WHERE \"queryid\"=~/^${queryid:regex}$/ AND \"host\" =~ /^${host:regex}$/ AND $timeFilter GROUP BY \"datname\")"
   },
   {
    "name": "usename",
    "label": "PostgreSQL User",
    "query": "SELECT DISTINCT(\"usename\") FROM (SELECT last(\"calls\") FROM \"${archive}\".\"pg_stat_statements_diff_1m_archive\" WHERE $timeFilter AND \"queryid\"=~/^${queryid:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/  GROUP BY \"usename\")"
   },
   {
    "name": "query_md5",
    "query": "SELECT DISTINCT(\"query_md5\") FROM (SELECT last(\"calls\") FROM \"${archive}\".\"pg_stat_statements_diff_1m_archive\" WHERE \"datname\" =~ /^${datname:regex}$/ AND \"queryid\" =~ /^${queryid:regex}$/  AND $timeFilter GROUP BY \"query_md5\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Сводная статистика по QueryID = ${queryid}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "usename" ], "type": "tag" },
      { "params": [ "queryid" ], "type": "tag" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Calls" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "rows" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Rows" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         " / sum(\"calls\")"
        ],
        "type": "math"
       },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "shared_blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Shared Hit" ], "type": "alias" }
      ],
      [
       { "params": [ "shared_blks_read" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Shared Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "usename" ], "type": "tag" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Calls" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "rows" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Rows" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         " / sum(\"calls\")"
        ],
        "type": "math"
       },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "shared_blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Shared Hit" ], "type": "alias" }
      ],
      [
       { "params": [ "shared_blks_read" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Shared Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "usename" ], "type": "tag" },
      { "params": [ "queryid" ], "type": "tag" },
      { "params": [ "query_md5" ], "type": "tag" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Calls" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "rows" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Rows" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         " / sum(\"calls\")"
        ],
        "type": "math"
       },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "shared_blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Shared Hit" ], "type": "alias" }
      ],
      [
       { "params": [ "shared_blks_read" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Shared Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Text of $query_md5",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "repeat": "query_md5",
   "targets": [
    {
     "groupBy": [
      { "params": [ "query" ], "type": "tag" }
     ],
     "measurement": "pg_stat_statements_diff",
     "query": "SELECT last(\"calls_sum\") as \"calls\" FROM \"$archive\".\"pg_stat_statements_query_1d\" WHERE (\"query_md5\" =~ /^${query_md5:regex}$/ AND \"queryid\" =~ /^${queryid:regex}$/ AND \"datname\" =~ /^${datname:regex}$/) GROUP BY \"query\"",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "query_md5", "operator": "=~", "value": "/^$query_md5$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"calls_sum\") as \"calls\" FROM \"1d\".\"pg_stat_statements_query_10m\" WHERE (\"query_md5\" =~ /^${query_md5:regex}$/ AND \"queryid\" =~ /^${queryid:regex}$/ AND \"datname\" =~ /^${datname:regex}$/) GROUP BY \"query\"\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Stats for QueryID = ${queryid}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sum: Query Duration / min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_query_md5 ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query_md5" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/($__interval_ms / 1000 / 60)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Query duration / DB duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Sum Duration per minute by Query",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "query": "SELECT sum(\"duration_10m\") as \"Sum Duration per minute by Query\" FROM \"$archive\".\"pg_stat_statements_query_md5\" WHERE (\"datname\" =~ /^$datname$/ AND \"host\" =~ /^$host$/ AND \"usename\" =~ /^$usename$/ AND \"queryid\" =~ /^$queryid$/ AND \"query_md5\" =~ /^$query_md5$/) AND $timeFilter GROUP BY time($__interval), \"query_md5\" fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "Sum Duration per minute by Query"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    },
    {
     "alias": "Sum Duration per minute by DB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "query": "SELECT sum(\"duration_10m\") as \"Sum Duration per minute by DB\" FROM \"$archive\".\"pg_stat_statements_query_md5\" WHERE (\"datname\" =~ /^$datname$/ AND \"host\" =~ /^$host$/ AND \"usename\" =~ /^$usename$/) AND $timeFilter GROUP BY time($__interval), \"query_md5\" fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Sum Duration per minute by DB" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg (Query Duration)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_query_md5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query_md5" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/sum(calls)" ], "type": "math" },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Calls",
   "type": "graph",
   "description": "Средняя интенсивность вызовов запроса за минуту.\nИзмеряется в запросах в сек (RPS)",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "$tag_query_md5 ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query_md5" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / ($__interval_ms / 1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Calls / DB Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "RPS Query",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    },
    {
     "alias": "RPS DB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg (Query Rows)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_query_md5 ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query_md5" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "rows" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/sum(calls)" ], "type": "math" },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Blk Hit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_query_md5 ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query_md5" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "shared_blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " /sum(calls)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Blk Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_query_md5 ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query_md5" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "shared_blks_read" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " /sum(calls)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Blk Dirtied",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_query_md5 ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query_md5" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "shared_blks_dirtied" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " /sum(calls)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  },
  {
   "title": "Shared Blk Writen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_query_md5 ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query_md5" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_statements_diff_1m_archive",
     "select": [
      [
       { "params": [ "shared_blks_written" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " /sum(calls)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "queryid", "operator": "=~", "value": "/^$queryid$/" }
     ]
    }
   ]
  }
 ]
}