{
 "title": "PostgreSQL Activity",
 "tags": [
  "influxdb",
  "PostgreSQL",
  "main"
 ],
 "time": { "from": "2020-11-11T12:24:09.228Z", "to": "2020-11-11T13:13:06.986Z" },
 "templating": {
  "list": [
   {
    "name": "current",
    "query": "/d/pgstat/postgresql-query-statistics"
   },
   {
    "name": "detail",
    "query": "/d/pgquery/postgresql-query-details"
   },
   { "name": "db_jmeter", "label": "DataBase for annotation", "query": "influxdb" },
   { "name": "db", "label": "DataBase", "query": "influxdb" },
   { "name": "archive", "label": "Retention policy (archive)", "query": "SHOW RETENTION POLICIES" },
   { "name": "new", "label": "Retention Policy (new)", "query": "SHOW RETENTION POLICIES" },
   {
    "name": "host",
    "label": "PostgreSQL host",
    "query": "SELECT DISTINCT(\"host\") FROM (SELECT last(\"count\") FROM \"${new}\".\"pg_stat_activity_count\"  WHERE $timeFilter GROUP BY \"host\")"
   },
   {
    "name": "datname",
    "label": "PostgreSQL DB",
    "query": "SELECT DISTINCT(\"datname\") FROM (SELECT last(\"count\") FROM \"${new}\".\"pg_stat_activity_count\" WHERE \"host\" =~ /^${host:regex}$/   AND $timeFilter GROUP BY \"datname\")"
   },
   {
    "name": "usename",
    "label": "PostgreSQL User",
    "query": "SELECT DISTINCT(\"usename\") FROM (SELECT last(\"count\") FROM \"${new}\".\"pg_stat_activity_count\" WHERE \"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/  AND $timeFilter GROUP BY \"usename\")"
   },
   {
    "name": "state",
    "label": "state",
    "query": "SELECT DISTINCT(\"state\") FROM (SELECT last(\"count\") FROM \"${new}\".\"pg_stat_activity_count\" WHERE \"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/  AND $timeFilter GROUP BY \"state\")"
   },
   { "name": "TOP", "query": "10,20,30,40,50,100,200" },
   { "name": "TOP_by", "label": "TOP by", "query": "Total, Max, Mean, Count" },
   {
    "name": "filter",
    "label": "Filter",
    "query": "SELECT \"query_md5\", top(\"${TOP_by}\", ${TOP}) \nFROM (SELECT sum(\"transaction_duration\") AS \"Total\", mean(\"transaction_duration\") AS \"Mean\", count(\"transaction_duration\") AS \"Count\" FROM \"$new\".\"pg_stat_activity\" WHERE (\"state\" = 'idle in transaction' AND \"host\" =~ /^$host$/ AND \"datname\" =~ /^$datname$/ AND \"usename\" =~ /^$usename$/) AND $timeFilter GROUP BY  \"query_md5\") "
   },
   { "name": "db_stat", "label": "DataBase Stat", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Idle in transaction - Sum Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Idle in transaction Duration by host",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"host\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by state",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"state\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by datname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"datname\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by usename",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"usename\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by host — datname — usename",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host — $tag_datname — $tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by usename — query_md5",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_usename — $tag_query_md5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_duration\") as \"state_duration\" FROM (\nSELECT sum(\"sum_idle_seconds\") as \"state_duration\" FROM \"7d\".\"pg_stat_activity_idle_in_transaction\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"datname\", \"state\", \"usename\", \"query_md5\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"usename\", \"query_md5\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by state — datname — usename — query_md5 — query",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "query" ], "type": "tag" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "sum_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "*1000.0" ], "type": "math" },
         { "params": [ "Sum" ], "type": "alias" }
        ],
        [
         { "params": [ "max_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ],
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Count" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction - Sum Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "Idle in transaction Connection Count by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity_idle_in_transaction",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction Connection Count by usename",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_usename",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "usename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity_idle_in_transaction",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction Connection Count by datname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity_idle_in_transaction",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction Connection Count by state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity_idle_in_transaction",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction Connection Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_datname - $tag_usename - $tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "usename" ], "type": "tag" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity_idle_in_transaction",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction - Avg Connection Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Idle in transaction Connection Duration by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity_idle_in_transaction",
     "select": [
      [
       { "params": [ "avg_connection_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction Connection Duration by usename",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_usename",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "usename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity_idle_in_transaction",
     "select": [
      [
       { "params": [ "avg_connection_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction Connection Duration by datname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity_idle_in_transaction",
     "select": [
      [
       { "params": [ "avg_connection_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction Connection Duration by state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity_idle_in_transaction",
     "select": [
      [
       { "params": [ "avg_connection_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction Connection Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_datname - $tag_usename - $tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "usename" ], "type": "tag" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_stat_activity_idle_in_transaction",
     "select": [
      [
       { "params": [ "avg_connection_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
      { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle in transaction - Avg Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Idle in transaction Duration by host",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by usename",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by datname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration by state",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "Idle in transaction Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host - $tag_datname - $tag_usename - $tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_idle_in_transaction",
       "select": [
        [
         { "params": [ "avg_idle_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "State Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "State Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_suration\") as \"state_suration\" FROM (\nSELECT sum(\"avg_state_seconds\") as \"state_suration\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"usename\", \"datname\", \"state\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"host\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "State Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_suration\") as \"state_suration\" FROM (\nSELECT sum(\"avg_state_seconds\") as \"state_suration\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"usename\", \"datname\", \"state\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"usename\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "State Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_suration\") as \"state_suration\" FROM (\nSELECT sum(\"avg_state_seconds\") as \"state_suration\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"usename\", \"datname\", \"state\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"datname\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "State Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"state_suration\") as \"state_suration\" FROM (\nSELECT sum(\"avg_state_seconds\") as \"state_suration\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/ AND \"state\" =~ /^${state:regex}$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"usename\", \"datname\", \"state\" fill(null)\n) WHERE $timeFilter \nGROUP BY time($__interval), \"state\"",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    },
    {
     "title": "State Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_host - $tag_datname - $tag_usename - $tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "select": [
        [
         { "params": [ "avg_state_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"count\") as \"count\" FROM (\nSELECT mean(\"count\") as \"count\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND $timeFilter GROUP BY time($__interval), \"state\", \"usename\", \"datname\", \"host\" fill(null)\n) WHERE $timeFilter GROUP BY time($__interval), \"host\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"count\") as \"count\" FROM (\nSELECT mean(\"count\") as \"count\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND $timeFilter GROUP BY time($__interval), \"state\", \"usename\", \"datname\", \"host\" fill(null)\n) WHERE $timeFilter GROUP BY time($__interval), \"datname\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"count\") as \"count\" FROM (\nSELECT mean(\"count\") as \"count\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND $timeFilter GROUP BY time($__interval), \"state\", \"usename\", \"datname\", \"host\" fill(null)\n) WHERE $timeFilter GROUP BY time($__interval), \"state\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_usename",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "query": "SELECT sum(\"count\") as \"count\" FROM (\nSELECT mean(\"count\") as \"count\" FROM \"7d\".\"pg_stat_activity_count\" WHERE (\"host\" =~ /^${host:regex}$/ AND \"datname\" =~ /^${datname:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND $timeFilter GROUP BY time($__interval), \"state\", \"usename\", \"datname\", \"host\" fill(null)\n) WHERE $timeFilter GROUP BY time($__interval), \"usename\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_datname - $tag_usename - $tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity_count",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Transaction Duration (state = idle in transaction)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_usename - $tag_wait_event - $tag_wait_event_type",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "wait_event" ], "type": "tag" },
        { "params": [ "wait_event_type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_activity",
       "select": [
        [
         { "params": [ "transaction_duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "state", "operator": "=", "value": "idle in transaction" }
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "query_md5" ], "type": "tag" }
       ],
       "measurement": "pg_stat_activity",
       "select": [
        [
         { "params": [ "transaction_duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "transaction_duration" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ],
        [
         { "params": [ "transaction_duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "transaction_duration" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "Count" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "state", "operator": "=", "value": "idle in transaction" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "query_md5" ], "type": "tag" },
        { "params": [ "query" ], "type": "tag" },
        { "params": [ "queryid" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements",
       "select": [
        [
         { "params": [ "calls" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Calls" ], "type": "alias" }
        ],
        [
         { "params": [ "rows" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Row mean" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics: Host / Database / User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Duration / min",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " *60 /( $__interval_ms / 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Calls / sec",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "  / ($__interval_ms / 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Duration / min",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " * 60 / ($__interval_ms / 1000)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Calls / sec",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_datname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "/ ($__interval_ms / 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "datname", "operator": "=~", "value": "/^$datname$/" }
       ]
      }
     ]
    },
    {
     "title": "$db Statistic",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_query_md5",
       "select": [
        [
         { "params": [ "calls_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Calls" ], "type": "alias" }
        ],
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "rows_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Rows" ], "type": "alias" }
        ],
        [
         { "params": [ "max_time_10m" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "duration_10m" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / sum(\"calls_10m\")"
          ],
          "type": "math"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics: Query - TOP ${TOP} by ${TOP_by}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "$db Statistic by query",
     "type": "table",
     "gridPos": { "h": 28, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "queryid" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_query_text",
       "query": "SELECT top(\"${TOP_by}\", ${TOP}), \"Calls\", \"Total\", \"Rows\",\"Mean\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\" FROM \n(\nSELECT sum(\"calls\") AS \"Calls\", sum(\"duration\") AS \"Total\", sum(\"rows\") AS \"Rows\", sum(\"duration\")  / sum(\"calls\") AS \"Mean\" FROM \"$new\".\"pg_stat_statements_diff\" WHERE (\"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND \"query\" =~/.*${filter:regex}.*/ AND  $timeFilter AND time > now()-$new GROUP BY \"host\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\"\n),\n(\nSELECT sum(\"calls\") AS \"Calls\", sum(\"duration\") AS \"Total\", sum(\"rows\") AS \"Rows\", sum(\"duration\")  / sum(\"calls\") AS \"Mean\" FROM \"$archive\".\"pg_stat_statements_diff\" WHERE (\"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND \"query\" =~/.*${filter:regex}.*/ AND $timeFilter AND time < now()-$new GROUP BY \"host\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\"\n)",
       "select": [
        [
         { "params": [ "query" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "query" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics: Query (multiline) - TOP ${TOP} by ${TOP_by}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "$db Statistic by query",
     "type": "table-old",
     "gridPos": { "h": 83, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "datname" ], "type": "tag" },
        { "params": [ "usename" ], "type": "tag" },
        { "params": [ "query" ], "type": "tag" }
       ],
       "measurement": "pg_stat_statements_analyse",
       "query": "SELECT \"Calls\", top(${TOP_by}, ${TOP}), \"Total\", \"Rows\",\"Mean\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\" FROM \n(\nSELECT sum(\"calls\") AS \"Calls\", sum(\"duration\") AS \"Total\", sum(\"rows\") AS \"Rows\", sum(\"duration\")  / sum(\"calls\") AS \"Mean\" FROM \"$new\".\"pg_stat_statements_diff\" WHERE (\"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND \"query\" =~/${filter:regex}/  AND $timeFilter AND time > now()-$new GROUP BY \"host\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\"\n),\n(\nSELECT sum(\"calls\") AS \"Calls\", sum(\"duration\") AS \"Total\", sum(\"rows\") AS \"Rows\", sum(\"duration\")  / sum(\"calls\") AS \"Mean\" FROM \"$archive\".\"pg_stat_statements_diff\" WHERE (\"datname\" =~ /^${datname:regex}$/ AND \"host\" =~ /^${host:regex}$/ AND \"usename\" =~ /^${usename:regex}$/) AND \"query\" =~/${filter:regex}/  AND $timeFilter AND time < now()-$new GROUP BY \"host\", \"datname\", \"usename\", \"queryid\", \"query_md5\", \"query\"\n)",
       "select": [
        [
         { "params": [ "calls" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Calls" ], "type": "alias" }
        ],
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Total" ], "type": "alias" }
        ],
        [
         { "params": [ "rows" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "Rows" ], "type": "alias" }
        ],
        [
         { "params": [ "max_time" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "Max" ], "type": "alias" }
        ],
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / sum(\"calls\")"
          ],
          "type": "math"
         },
         { "params": [ "Mean" ], "type": "alias" }
        ],
        [
         { "params": [ "shared_blks_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / ( sum(\"shared_blks_hit\") + sum(\"shared_blks_read\"))"
          ],
          "type": "math"
         },
         { "params": [ "% Shared Hit" ], "type": "alias" }
        ],
        [
         { "params": [ "local_blks_hit" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [
           " / ( sum(\"local_blks_hit\") + sum(\"local_blks_read\"))"
          ],
          "type": "math"
         },
         { "params": [ "% Local Hit" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "datname", "operator": "=~", "value": "/^$datname$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "usename", "operator": "=~", "value": "/^$usename$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}