apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "helm.fullname" . }}-config"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  telegraf.conf: |
    {{- .Files.Get "files/telegraf.conf" | nindent 4 }}
  {{- range $path, $_ := .Files.Glob "files/telegraf.d/*.conf" }}
  {{ base $path }}: |
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "helm.fullname" . }}-sql"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "files/sql/*.sql" }}
  {{ base $path }}: |
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
