#!/bin/sh -x

DB=telegraf_pg_activity_demo

influx <<-EOSQL
CREATE DATABASE "$DB";
EOSQL

influx <<-EOSQL
CREATE RETENTION POLICY "archive" ON "$DB" DURATION 1000d REPLICATION 1 SHARD DURATION 1d;
EOSQL

influx <<-EOSQL
CREATE RETENTION POLICY "7d" ON "$DB" DURATION 7d REPLICATION 1 SHARD DURATION 1h DEFAULT;
EOSQL