apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.100-192.168.99.149
    - name: application-ip
      protocol: layer2
      addresses:
      - 192.168.99.150-192.168.99.150
    - name: nexus-ip
      protocol: layer2
      addresses:
      - 192.168.99.151-192.168.99.151
    - name: teamcity-server-ip
      protocol: layer2
      addresses:
      - 192.168.99.152-192.168.99.152
    - name: grafana-ip
      protocol: layer2
      addresses:
      - 192.168.99.153-192.168.99.153